pub mod accelerator;
pub mod bench;
pub mod bitset;
pub mod claim;
pub mod corpus;
pub mod predicates;
pub mod ranking;
pub mod verifier;
pub mod vector;
pub mod truth_shield;

pub use accelerator::{available_backends, fused_and_popcount_3way_resident, fused_and_popcount_3way_resident_parallel, fused_and_popcount_3way_resident_mode, ComputeBackend, KernelReport};
pub use bench::{run_large_corpus_bench, LargeCorpusBenchReport};
pub use claim::{map_claim_to_predicates, ClaimPredicatePlan};
pub use corpus::{BitsetCorpus, Paper, QueryResult};
pub use predicates::{build_registry, load_predicate_pack, Predicate, PredicateKind};
pub use ranking::{rank_results, RankedCitation};
pub use truth_shield::{verify_and_retrieve, EvidenceVerdict, TruthShieldReport};
pub use verifier::{SentenceVerdict, VerificationKernel, VerificationReport};
pub use vector::{VectorHit, VectorIndex};
